# Generated by Django 5.0.4 on 2024-04-15 22:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interest_rate', models.DecimalField(decimal_places=1, max_digits=5)),
                ('loan_type', models.CharField(max_length=20)),
                ('loan_amount', models.IntegerField()),
                ('term_period', models.IntegerField()),
                ('disbursement_date', models.DateField()),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='open', max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
